### ISSUE TITLE
How to test filebeat httpjson module

### ISSUE THREAD

**Issue by TomonoriSoejima** [TomonoriSoejima/Tejun#135]

**Comment by TomonoriSoejima** [comment]
- sample json
```
{
    "name":"tomo",
    "test_score" : [10, 20, 30]
}
```
- filebeat config

```
filebeat.inputs:
- type: httpjson
  interval: 1m
  request.url: "http://127.0.0.1:5000/get_data"
  response.transforms:
    - set:
        target: body.my_name
        value: '[[.cursor.my_name]]'
    - set:
        target: body.my_lastname
        value: '[[.cursor.my_lastname]]'
    - set:
        target: body.my_highscore
        value: '[[.cursor.my_highscore]]'               
  cursor:
    my_name:
      value: "[[.last_response.body.name]]"
    my_lastname:
      value: "soejima"
    my_highscore:
      value: "[[.last_response.body.test_score]]"
  processors:
    - decode_json_fields:
        fields: ["message"]
        target: "json"

cloud.id: new:YXNpYS1ub3J0aGVhc3QxLmdjcC5jbG91ZC5lcy5pbzo0NDMkNzgzNGVmZTIzNGM3NDMyYjk4ZTNmY2E2MTdjYTZhYjYkOGUxOWNhZGIwNDc5NDQzOGJiZWYwMzdhMjVmY2NiZWM=
cloud.auth: elastic:Yvne2eq21qGVNilGYaeYXSpL
```

- response
```
{
  "_index": ".ds-filebeat-8.9.0-2023.08.17-000001",
  "_id": "g6l4AooB_0c3VRz_Nzxj",
  "_score": null,
  "_source": {
    "@timestamp": "2023-08-17T07:49:01.513Z",
    "event": {
      "created": "2023-08-17T07:49:01.513Z"
    },
    "message": "{\"my_lastname\":\"soejima\",\"my_name\":\"tomo\",\"name\":\"tomo\",\"test_score\":[10,20,30]}",
    "input": {
      "type": "httpjson"
    },
    "json": {
      "my_lastname": "soejima",
      "my_name": "tomo",
      "name": "tomo",
      "test_score": [
        10,
        20,
        30
      ]
    },
    "host": {
      "name": "surfer-3.local"
    },
    "agent": {
      "type": "filebeat",
      "version": "8.9.0",
      "ephemeral_id": "7beea202-0178-4f2c-884e-311fb5a91559",
      "id": "5188af1a-8ae4-4a0e-ab27-28b03988cb5a",
      "name": "surfer-3.local"
    },
    "ecs": {
      "version": "8.0.0"
    }
  },
  "sort": [
    1692258541513
  ]
}
```
