### ISSUE TITLE
How to make custom index name in filebeat version 7

### ISSUE THREAD

**Issue by TomonoriSoejima** [TomonoriSoejima/Tejun#159]
## 1 make ILM policy

```

PUT /_cluster/settings
{
    "persistent" : {
        "indices.lifecycle.poll_interval": "2s"
    }
}


PUT _ilm/policy/filebeat-mysuffix
{
  "policy": {
    "phases": {
       "hot": {
        "min_age": "0s",
        "actions": {
          "set_priority": {
            "priority": 100
          }
        }
      },
      "delete": {
        "min_age": "90d",
        "actions": {
          "delete": {
            "delete_searchable_snapshot": true
          }
        }
      }
    }
  }
}

# make template

PUT _template/filebeat-mysuffix
{
  "index_patterns": ["filebea-mysuffix-*"],
  "settings": {
    "lifecycle": {
      "name": "filebeat-mysuffix"
    },
    "number_of_shards": 1,
    "number_of_replicas": 0
  }


# make boostramp index

PUT filebeat-mysuffix-000001
{
  "aliases": {
    "filebeat-mysuffix": {
      "is_hidden": true
    }
  }
}


```

- filebeat.yml

```
filebeat.inputs:
  - type: log
    id: my-file-id
    enabled: true
    paths:
      - /Users/surfer/cases/01408442/tomo.log
filebeat.config.modules:
  path: '${path.config}/modules.d/*.yml'
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana: null
output.elasticsearch:
  hosts:
    - 'localhost:9200'
  indices:
    - index: filebeat-mysuffix
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: null
  - add_docker_metadata: null
  - add_kubernetes_metadata: null
setup.template.pattern: filebeat-mysuffix-*
setup.ilm.enabled: false
```
