### ISSUE TITLE
How to test kibana log rotation

### ISSUE THREAD

**Issue by TomonoriSoejima** [TomonoriSoejima/Tejun#82]
```
logging:
  appenders:
    rolling-file:
      type: rolling-file
      fileName: /Users/surfer/elastic/labs/7.17.0/kibana/kibana.log
      policy:
        type: time-interval
        interval: 10s
        modulate: true
      strategy:
        type: numeric
        pattern: '-%i'
        max: 7
      layout:
        type: pattern
  root:
    appenders: [default, rolling-file]
```
