### ISSUE TITLE
How to play with kafka

### ISSUE THREAD

**Issue by TomonoriSoejima** [TomonoriSoejima/Tejun#92]
I read https://qiita.com/greenteabiscuit/items/8e96573324437a07b62d

**Comment by TomonoriSoejima** [comment]
To install java

- install sdkman first
https://github.com/sdkman/homebrew-tap

- check which JDK to install.
   we want oracle java
`sdk list java | grep oracle`



```
[surfer-2:~]$ sdk list java | grep oracle
 Oracle        |     | 19.0.1       | oracle  |            | 19.0.1-oracle       
               | >>> | 17.0.5       | oracle  | installed  | 17.0.5-oracle       
[surfer-2:~]$ 
```

- install this JDK

```
sdk install java  17.0.5-oracle # install JDK
sdk current java # check the current JDK
sdk home java 17.0.5-oracle # check the current path
export JAVA_HOME=$(sdk home java 17.0.5-oracle) # change JAVA_HOME accordingly.
```


send events to kafka ( I gave up in docker way and I did the followings)

## First download [kafka](https://www.apache.org/dyn/closer.cgi?path=/kafka/3.3.1/kafka_2.13-3.3.1.tgz)

### follow steps at https://kafka.apache.org/quickstart

`bin/kafka-console-producer.sh --topic test  --bootstrap-server localhost:29092`


kafka is already up witth docker-compose.yml looking like this.


```
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
```
